// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU45N8cX4n16am7k6lnbO8pPW6lTkZ8tk',
    appId: '1:744814192296:web:6d682043a8dbabb022849d',
    messagingSenderId: '744814192296',
    projectId: 'exp-app-08',
    authDomain: 'exp-app-08.firebaseapp.com',
    storageBucket: 'exp-app-08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaC2RbubwXR3OK-4j_YjH8kO9VsGLOQMM',
    appId: '1:744814192296:android:98b9db6ff949265422849d',
    messagingSenderId: '744814192296',
    projectId: 'exp-app-08',
    storageBucket: 'exp-app-08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0mf09zDt3SGKkXP0ux46rtqi3WW_ovWE',
    appId: '1:744814192296:ios:71aaf8da821155aa22849d',
    messagingSenderId: '744814192296',
    projectId: 'exp-app-08',
    storageBucket: 'exp-app-08.appspot.com',
    iosBundleId: 'com.example.experimentalApp',
  );
}
